// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.vtc.server;

public final class Server_Stub
    extends java.rmi.server.RemoteStub
    implements com.vtc.UserService
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_findUser_0;
    private static java.lang.reflect.Method $method_sayHello_1;
    
    static {
	try {
	    $method_findUser_0 = com.vtc.UserService.class.getMethod("findUser", new java.lang.Class[] {int.class});
	    $method_sayHello_1 = com.vtc.UserService.class.getMethod("sayHello", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public Server_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of findUser(int)
    public com.vtc.User findUser(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_findUser_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -4257938762018168018L);
	    return ((com.vtc.User) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of sayHello()
    public java.lang.String sayHello()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_sayHello_1, null, 6043973830760146143L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
